### ISSUE TITLE
Error displaying text on two dialogue screens

### ISSUE THREAD

**Issue by GomiHiko** [SunTheCourier/Splatoon-2-Meme-Mod#17]
![GitHawk Upload by GomiHiko](https://i.imgur.com/Cgvqpnl.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GomiHiko** [comment]
![GitHawk Upload by GomiHiko](https://i.imgur.com/NV1fES3.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SunTheCourier** [comment]
Thanks for making this issue for me i'll fix this when I can.

**Comment by SunTheCourier** [comment]
Fixed
