### ISSUE TITLE
Some dud/one of the creators of the mod from the Splatoon Modding Hub discord server told me to request to change a line callie says in the final boss

### ISSUE THREAD

**Issue by CCBM-Geo** [SunTheCourier/Splatoon-2-Meme-Mod#32]
Callie says "Lets hit 'em with our hit single: Bitch Run Bitch!" and it should say "Lets hit 'em with our hit single: Boob Rash Bitch!" since it is the name of the level. I really don't care about this, someone told me to request this.

**Comment by SunTheCourier** [comment]
Fixed
